-- ============================================================
-- Seed: AI brain files (editable in the AI page)
-- ============================================================

INSERT INTO ai_context_files (name, description, content, sort_order) VALUES

('Company Profile',
 'Who Gulf Life Concierge is, what they do, their market and values.',
 E'# Gulf Life Concierge — Company Profile\n\n## Who We Are\nGulf Life Concierge is a luxury vacation rental and property management company serving the 30A Gulf Coast of Florida. We connect discerning travelers and property owners with premium properties in Rosemary Beach, Alys Beach, WaterColor, WaterSound, Seaside, and surrounding communities.\n\n## What We Do\n- **Property Management for Owners**: Full-service management of high-end Gulf Coast rental properties — marketing, bookings, guest care, maintenance coordination, revenue optimization\n- **Vacation Rentals for Guests**: Premium stays with white-glove concierge service\n- **Concierge Services**: Personalized trip planning, local recommendations, VIP experiences\n\n## Two Audiences in This CRM\n1. **Owner leads** — homeowners on 30A who could hire us to manage their rental property. This is the sales pipeline.\n2. **Guests** — past and current renters imported from Streamline. This is the marketing database for repeat bookings.\n\n## Our Differentiators\n- Deep local knowledge of every neighborhood on 30A\n- White-glove service from inquiry to checkout\n- Personal relationships: owners and guests have a real human they can call\n- Modern booking platform (Streamline) with a premium web presence',
 1),

('Communication Style',
 'How we write and speak with leads — tone, voice, phrases to use and avoid.',
 E'# Communication Style Guide\n\n## Core Tone\n**Warm, confident, and personal.** We are not a corporate sales team — we are local experts who love where we live. Every message should feel like it came from a knowledgeable friend, not a salesperson.\n\n## Voice Principles\n- **Personal**: Use their name. Reference what they told us.\n- **Experiential**: Talk about outcomes. For owners: "your place earning while you''re away, cared for like we live there." For guests: "waking up to the sound of the Gulf."\n- **Low pressure**: We never push. We invite.\n- **Concise**: 3 short paragraphs max for emails. 1–2 sentences for texts.\n- **Warm closing**: Always end with an easy, low-pressure next step.\n\n## Phrases We Use\n- "I wanted to reach out personally..."\n- "Based on what you shared with us..."\n- "Whenever you''re ready..."\n- "Happy to answer any questions at all."\n\n## Phrases We Avoid\n- "Just following up" / "Circling back" / "Touching base"\n- "Per my last email"\n- Excessive exclamation points\n- False urgency ("Act now!")\n\n## Signature\nSign with first name only. Warmth carries it.',
 2),

('Sales Process — Owner Leads',
 'Pipeline stages for homeowner leads and how to work each one.',
 E'# Owner Lead Sales Process\n\nOwner leads are homeowners on 30A who could hire Gulf Life Concierge to manage their rental property.\n\n## Pipeline Stages\n1. **New** — Just identified or inquired. Goal: first personal contact within 24 hours.\n2. **Contacted** — First touch made. Goal: learn about their property, current management situation, and pain points.\n3. **Nurturing** — Interested but not ready. Goal: stay top of mind with value — revenue estimates, market updates, local news. Follow up every 7–10 days.\n4. **Proposal** — Management proposal delivered. Goal: answer objections, close within 2 weeks.\n5. **Closed Won** — Signed management agreement. Onboard the property.\n6. **Closed Lost** — Went elsewhere or not now. Note why, keep the door open — check back in 6 months.\n\n## What Owners Care About\n- **Net revenue** — what actually hits their account after fees\n- **Property care** — someone local who treats it like their own\n- **Transparency** — clear statements, no surprise charges\n- **Low hassle** — they never want a 2am guest call\n\n## Common Objections\n- **"I already have a manager"**: Ask what they''d improve. Position a free revenue analysis.\n- **"Fees are too high"**: Reframe on net income — better marketing and pricing usually out-earns the fee difference.\n- **"I rent it myself"**: Respect it. Quantify their hours + missed midweek bookings. Offer to run the numbers.\n\n## Guests (Marketing Database)\nGuests imported from Streamline are NOT pipeline leads. They are past renters — the goal is repeat bookings and referrals via email/SMS campaigns (Mailchimp + Quo).',
 3),

('Properties & Market',
 'Key info about the 30A market, property types, pricing ranges, and neighborhoods.',
 E'# 30A Market & Properties\n\n## The 30A Corridor\n30A is a scenic highway along the Gulf Coast of Northwest Florida running through some of the most exclusive beach communities in the Southeast — sugar-white sand, emerald water, planned communities with distinct characters.\n\n## Key Communities\n- **Rosemary Beach**: Upscale, walkable, European-inspired. Premium pricing.\n- **Alys Beach**: Ultra-luxury, all-white architecture. Highest price point.\n- **WaterColor**: State-park adjacent, laid-back luxury, family favorite.\n- **WaterSound**: Quieter, newer, privacy-seekers.\n- **Seaside**: Iconic planned community, vibrant town center.\n- **Grayton Beach**: Rustic, bohemian, old-Florida character.\n\n## Weekly Rental Pricing\n- 2BR/smaller: $2,000–$5,000\n- 3–4BR standard: $4,000–$8,000\n- 4–5BR premium/Gulf-front: $7,000–$15,000\n- Estate/Gulf-front luxury: $15,000–$25,000+\n\n## Seasons\n- **Peak**: Memorial Day – Labor Day\n- **Shoulder**: Spring Break, October\n- **Off-peak**: November–February\n\n## What Guests Want Most\nGulf-front/view, private pool, walkability, room for large groups, pet-friendly.',
 4)

ON CONFLICT DO NOTHING;
